services:
  web:
    container_name: web
    build: .
    volumes:
      - .:/var/www/html
    expose:
      - "9000"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: skullking_user
      MYSQL_PASSWORD: SkullKing_2025!
      MYSQL_DATABASE: skull_king_league
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - web
    links:
      - "web:web"
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: skull_king_league
      MYSQL_USER: skullking_user
      MYSQL_PASSWORD: SkullKing_2025!
    ports:
      - "3306:3306"
    volumes:
    - db_data:/var/lib/mysql
volumes:
  db_data:
    driver: local

